In [1]:
!nvidia-smi -L

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 36 42 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [ ]:
import numpy as np

A = [[1,3,4],[2,5,7],[5,9,6]] 
A = np.array(A)
B = [[1,0,0],[0,1,0],[0,0,1]]
B = np.array(B)
print(A,B)

[[1 3 4]
 [2 5 7]
 [5 9 6]] [[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
# here A and B are list of lists
def matrix_mul(A, B):
    # write your code

    A_m, A_n = A.shape[0],A.shape[1]
    B_m, B_n = B.shape[0],B.shape[1]

    if A_n != B_m:
        print("Multiplication not possible")
        return
    C = np.zeros((A_m,B_n),dtype =  np.int64)

    for i in range(A_m):
        for j in range(B_n):
            for k in range(B_m):
                C[i][j] += A[i][k]*B[k][j]




    return(C)


A = np.array([[1,2],
              [3,4]])

B = np.array([[1,4],
              [5,6],
              [7,8],
              [9,6]])

print(matrix_mul(A, B))

Multiplication not possible
None


<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [ ]:
from random import uniform
from collections import Counter
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
def pick_a_number_from_list(A):
    
    A = np.sort(A)
    B = A.copy()
    B = np.cumsum(B)
    totalsum = np.sum(A)
    B = B/totalsum

    x = np.random.uniform(0,1,1)
    print(x)
    for i in range(len(B)):
        if i == 0:
            if x < B[i]:
                return A[i]
        if x > B[i-1] and x < B[i]:
            return A[i]
        if i == len(B)-1:
            return A[-1]

def sampling_based_on_magnitued():
    l = []
    for i in range(1,100):
        number = pick_a_number_from_list(A)
        l.append(number)
        print(number)
    print(Counter(l))

A = [0 ,5 ,27 ,6 ,13 ,28 ,100,45,10,79]
sampling_based_on_magnitued()

[0.31701954]
45
[0.33293917]
45
[0.40408193]
45
[0.46071551]
79
[0.8881484]
100
[0.72736601]
100
[0.12990432]
27
[0.84225246]
100
[0.42857093]
79
[0.69600319]
100
[0.73981662]
100
[0.66733476]
79
[0.76710668]
100
[0.44804636]
79
[0.65585812]
79
[0.69923759]
100
[0.42584839]
45
[0.02677966]
6
[0.77305384]
100
[0.12805056]
27
[0.76180173]
100
[0.41810068]
45
[0.69603659]
100
[0.14844015]
27
[0.06456713]
10
[0.18735377]
27
[0.34012249]
45
[0.3458813]
45
[0.51819603]
79
[0.29396337]
45
[0.88133738]
100
[0.82148668]
100
[0.47461358]
79
[0.48382389]
79
[0.40800597]
45
[0.68536678]
100
[0.09641739]
13
[0.05315359]
10
[0.20099783]
28
[0.1066497]
13
[0.63214217]
79
[0.96740747]
100
[0.67858263]
79
[0.69918914]
100
[0.48030275]
79
[0.26825891]
28
[0.49123812]
79
[0.99034709]
100
[0.62144844]
79
[0.56018532]
79
[0.99315554]
100
[0.1289169]
27
[0.20772516]
28
[0.39105794]
45
[0.66683959]
79
[0.32018212]
45
[0.46986086]
79
[0.81448017]
100
[0.92789294]
100
[0.39912881]
45
[0.50124971]
79
[0.9590478

<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [ ]:
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
# String: it will be the input to your program
def replace_digits(s):
    # write your code
    s = re.sub('[^0-9]','',s)
    s = re.sub('[0-9]','#',s)
    # print(s)
    # 
    
    return(s) # modified string which is after replacing the # with digits
s = '#2a$#b%c%561# '
print(replace_digits(s))

####


<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [2]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
def display_dash_board(students, marks):
    # write code for computing top top 5 students
    for i in range(len(marks)-1):
        for j in range(0,len(marks)-i-1):
            if marks[j] > marks[j+1]:
                marks[j],marks[j+1] = marks[j+1],marks[j]
                students[j],students[j+1] = students[j+1],students[j]

    # write code for computing top least 5 students
    return top_5_students, least_5_students, students_within_25_and_75, marks_within_25_and_75

students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10']
marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
top_5_students, least_5_students, students_within_25_and_75, marks_within_25_and_75 = display_dash_board(students, marks)

print("The top 5 students are: ")
for i in range(-1,-6,-1):
    print('{} {}'.format(students[i],marks[i]))

print()
print('*'*30)
print("The bottom 5 students are: ")
for i in range(5):
    print('{} {}'.format(students[i], marks[i]))

print()
print('*'*30)
print("The student in range of 25 to 75 percentile are ")
for i in range(int(25*len(marks)//100),int(75*len(marks)//100)):
    print('{} {}'.format(students[i], marks[i]))

The top 5 students are: 
student8 98
student10 80
student2 78
student5 48
student7 47

******************************
The bottom 5 students are: 
student3 12
student4 14
student9 35
student6 43
student1 45

******************************
The student in range of 25 to 75 percentile are 
student9 35
student6 43
student1 45
student7 47
student5 48


<h3> Q5: Find the closest points</h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [7]:
import math

# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can free to change all these codes/structure


# here S is list of tuples and P is a tuple ot len=2
def closest_points_to_p(S, P):
    # write your code here
    distance = []
    for point in S:
        dist = math.acos((point[0]*P[0]+point[1]*P[1])/(math.sqrt(point[0]**2+point[1]**2)*math.sqrt(P[0]**2+P[1]**2)))
        distance.append([point, dist])
    
    distance = sorted(distance,key = lambda x: x[1])
    closest_points_to_p = [distance[i][0] for i in range(5)]



    return closest_points_to_p  # its list of tuples

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)
points = closest_points_to_p(S, P)
print(points) #print the returned values

[(6, -7), (1, -1), (6, 0), (-5, -8), (-1, -1)]


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [11]:
import math
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def i_am_the_one(red,blue,line):
    # your code
    
    coef = [float(i) for i in re.split(r'[xy]',line)]
    flag = True
    count = 0
    for red_points in red:
        sign = red_points[0]*coef[0]+red_points[1]*coef[1]+coef[2]
        print(red_points,'=',sign, end = ' ')
        if sign >= 0:
            sign = 1
        else:
            sign = -1
        
        if count == 0 and sign == 1:
            flag = True
        elif count == 0 and sign == -1:
            flag == False
        
        elif count != 0:
            if sign == 1 and flag == False:
                return "NO"
            elif sign == 0 and flag == True:
                return "NO"

        count += 1
        print()
    
    print()
    
    flag = True
    count = 0
    for blue_point in blue:
        sign = blue_point[0]*coef[0]+blue_point[1]*coef[1]+coef[2]
        print(blue_point,'=',sign,end = ' ')
        if sign >= 0:
            sign = 1
        else:
            sign = -1
        
        if count == 0 and sign == 1:
            flag = True
        elif count == 0 and sign == -1:
            flag == False
        
        elif count != 0:
            if sign == 1 and flag == False:
                return "NO"
            elif sign == 0 and flag == True:
                return "NO"
        count += 1
        print()
    return "YES"

Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

for i in Lines:
    yes_or_no = i_am_the_one(Red, Blue, i)
    print(yes_or_no) # the returned value

(1, 1) = 2.0 
(2, 1) = 3.0 
(4, 2) = 6.0 
(2, 4) = 6.0 
(-1, 4) = 3.0 

(-2, -1) = -3.0 
(-1, -2) = -3.0 
(-3, -2) = -5.0 
(-3, -1) = -4.0 
(1, -3) = -2.0 
YES
(1, 1) = 0.0 
(2, 1) = 1.0 
(4, 2) = 2.0 
(2, 4) = -2.0 
(-1, 4) = -5.0 

(-2, -1) = -1.0 
(-1, -2) = 1.0 
(-3, -2) = -1.0 
(-3, -1) = -2.0 
(1, -3) = 4.0 
YES
(1, 1) = -2.0 
(2, 1) = -1.0 
(4, 2) = 1.0 
(2, 4) = -1.0 
(-1, 4) = -4.0 

(-2, -1) = -5.0 
(-1, -2) = -4.0 
(-3, -2) = -6.0 
(-3, -1) = -6.0 
(1, -3) = -2.0 
YES
(1, 1) = 0.5 
(2, 1) = 0.5 
(4, 2) = 1.5 
(2, 4) = 3.5 
(-1, 4) = 3.5 

(-2, -1) = -1.5 
(-1, -2) = -2.5 
(-3, -2) = -2.5 
(-3, -1) = -1.5 
(1, -3) = -3.5 
YES


In [30]:
import math
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def i_am_the_one(red,blue,line):
    # your code
    
    coef = [float(i) for i in re.split(r'[xy]',line)]


    flag = True
    count = 0
    sign_red = 0
    for red_points in red:
        sign_red = red_points[0]*coef[0]+red_points[1]*coef[1]+coef[2]
        # print(red_points,'=',sign, end = ' ')
        if sign_red >= 0:
            sign_red = 1
        else:
            sign_red = -1
        
        if count == 0 and sign_red == 1:
            flag = True
        elif count == 0 and sign_red == -1:
            flag = False
        
        if count != 0:
            if sign_red == 1 and flag == False:
                return "NO"
            elif sign_red == 0 and flag == True:
                return "NO"
        count += 1
        # print()
    
    
    flag = True
    count = 0
    sign_blue = 0
    for blue_point in blue:
        sign_blue = blue_point[0]*coef[0]+blue_point[1]*coef[1]+coef[2]
        # print(blue_point,'=',sign,end = ' ')
        if sign_blue >= 0:
            sign_blue = 1
        else:
            sign_blue = -1
        if count == 0 and sign_blue == 1:
            flag = True
        elif count == 0 and sign_blue == -1:
            flag = False
        
        if count != 0:
            if sign_blue == 1 and flag == False:
                return "NO"
            elif sign_blue == 0 and flag == True:
                return "NO"
        count += 1
        # print()
    if sign_red == sign_blue:
        return "NO"
    else:
        return "YES"

Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

for i in Lines:
    yes_or_no = i_am_the_one(Red, Blue, i)
    # print()
    print(yes_or_no) # the returned value
    # print()

YES
NO
NO
YES


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [39]:
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def curve_smoothing(string):
    # your code
    string = string.split(',')
    i,j = 0,0
    temp = 0
    prev = -1
    for i in range(len(string)):
        if string[i] != '_':
            if int(string[i]) >= 0:
                if prev == -1:
                    temp = int(string[i])//((i+1)-j)
                    prev = i
                else:
                    temp = (int(string[i])+int(string[prev]))//((i+1)-j)
                while j <= i:
                    string[j] = temp
                    j += 1
                j -= 1
    
    if j != i:
        temp = string[prev]//((i+1)-j)
        while j <= i:
            string[j] = temp
            j += 1
    string = [str(string[i]) for i in range(len(string))]
    string = ",".join(string)
    return string

S=  "_,_,30,_,_,_,50,_,_"
smoothed_values= curve_smoothing(S)
print(smoothed_values)

10,10,12,12,12,12,4,4,4


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [87]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings



# you can free to change all these codes/structure
def compute_conditional_probabilites(A):
    # your code
    hashmap = {}
    F = set()
    S = set()
    for i in range(len(A)):
        # if hashmap.get(A[i][0],0) == 0:
        F.add(A[i][0])
        S.add(A[i][1])
        hashmap[(A[i][0],A[i][1])] = hashmap.get(A[i][0],0)+1
        hashmap[A[i][1]] = hashmap.get(A[i][1],0)+1

    F,S = list(F),list(S)
    
    for i in range(len(F)):
        for j in range(len(S)):
            # print(F[i],S[j])
            print('P(F={}|S=={})={}/{}'.format(F[i],S[j],hashmap.get((F[i],S[j]),0),hashmap.get(S[j]),end=' '))
        print()


    # print the output as per the instructions

A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]

compute_conditional_probabilites(A)

P(F=F3|S==S3)=1/3
P(F=F3|S==S2)=1/3
P(F=F3|S==S1)=0/4

P(F=F5|S==S3)=0/3
P(F=F5|S==S2)=0/3
P(F=F5|S==S1)=1/4

P(F=F4|S==S3)=1/3
P(F=F4|S==S2)=0/3
P(F=F4|S==S1)=1/4

P(F=F2|S==S3)=1/3
P(F=F2|S==S2)=1/3
P(F=F2|S==S1)=1/4

P(F=F1|S==S3)=0/3
P(F=F1|S==S2)=1/3
P(F=F1|S==S1)=1/4



<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [91]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(S1, S2):
    # your code
    count = 0
    word_in_s1_not_in_s2 = []
    word_in_s2_not_in_s1 = []
    s1 = set(S1.split(" "))
    s2 = set(S2.split(" "))

    count = len(s1.intersection(s2))
    for word in s1:
        if word not in s2:
            word_in_s1_not_in_s2.append(word)
    
    for word in s2:
        if word not in s1:
            word_in_s2_not_in_s1.append(word)

    return count, word_in_s1_not_in_s2,word_in_s2_not_in_s1

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
a,b,c = string_features(S1, S2)
print(a)
print(b)
print(c)

7
['first', '5', 'F']
['second', 'S', '3']


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [20]:
import math
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def compute_log_loss(A):
    # your code
    log_loss = 0
    for i in range(len(A)):
        # print(A[i][0],A[i][1])
        log_loss += -(A[i][0]*math.log(A[i][1]))
    log_loss /= len(A)
    
    return log_loss

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
# A = [[.1, .9], [.9, .1], [.8, .2], [.35, .65]]
loss = compute_log_loss(A)
print(loss)

0.4434224864800296
